# Generated by Django 4.0.4 on 2022-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
    ]
