# Generated by Django 4.0.4 on 2022-05-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='mail',
        ),
    ]
