# Generated by Django 4.0.4 on 2022-05-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_details_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Location',
        ),
    ]
